[mongodb]
mongodb-dev.krishsky.online

[catalogue]
catalogue-dev.krishsky.online

[redis]
redis-dev.krishsky.online

[user]
user-dev.krishsky.online

[cart]
cart-dev-krishsky.online

[mysql]
mysql-dev-krishsky.online

[rabbitmq]
rabbitmq-dev.krishsky.online

[payment]
payment-dev.krishsky.online

[frontend]
frontend-dev.krishsky.online



[all:vars]
ansible_user=ec2-user 
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.krishsky.online
CATALOGUE_HOST=catalogue-dev.krishsky.online
REDIS_HOST=redis-dev.krishsky.online
USER_HOST=user-dev.krishsky.online
CART_HOST=cart-dev.krishsky.online
MYSQL_HOST=mysql-dev.krishsky.online
SHIPPING_HOST=shipping-dev.krishsky.online
RABBITMQ_HOST=rabbitmq-dev.krishsky.online
PAYMENT_HOST=payment-dev.krishsky.online